# Generated by Django 4.0.4 on 2022-05-19 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Locomotives', '0002_constructeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='locomotive',
            name='Constructeur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Locomotives.constructeur'),
        ),
    ]
